include $(CURDIR)/../Config.mk

OBJS 	+= $(patsubst %.c,%.o,$(wildcard net/*.c))
OBJS 	+= $(patsubst %.S,%.o,$(wildcard net/*.S))


default: $(OBJS)
	$(LD) $(LDFLAGS) -r -o built_in.o $^



clean:


%.o: %.c $(HDRS) Makefile
	$(CC) $(CFLAGS) -c $< -o $@

%.o: %.S $(HDRS) Makefile
	$(CC) $(CFLAGS) $(AFLAGS) -D__ASSEMBLY__ -c $< -o $@



